# Release verification against OpenShift CI keys signed by the CI infrastructure
apiVersion: v1
data:
  store-openshift-ci-release: https://storage.googleapis.com/openshift-ci-release/releases/signatures/openshift/release
  verifier-public-key-openshift-ci: |-
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mQENBFy9Q6sBCAD1MvcwX9f1Vu/M/dh+SJYbuAP4urtZZ7YoZOlzo6lw/xDF9z0E
    ef8BXAtO7YMStfbxn5Rqb3kPnA20CRXraW4PqA5mB37ubDGThxb8catCTeWpd/5o
    mrbjLMrKCpg0ODfTgNZYj9gRDyDTKPjlW2xjX9Cmj/lmmGPYDG4qdrNpeicmMjpY
    XyYDVxFTRFMdifxTjHQRT5R9Pdq8WDFLrd3ZZWo4fN5Rb+ByWh8MusHj+FyHxA4J
    fD/G6VHyn19T7xT/g53JfPobKLdaoXKdSaorCYKWuyGaGyLStAn1MXgchswcBZcU
    92EegcoZY8K3cYhRbw7rQUUkx3p0yviS1DrPABEBAAG0DG9wZW5zaGlmdC1jaYkB
    VAQTAQgAPhYhBNBHYbEWIDsMCFm2Fii3bgW5I4iOBQJcvUOrAhsDBQkDwmcABQsJ
    CAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJECi3bgW5I4iOqwUH+wTRXXZkB6PdksQ2
    tF/x3vT3YAp1Fvm+aBt0L3+nUyI4W4wWmCvQ9mYqkXMDSx8rgSwMtwwJe7xJBkA1
    fK8CoPeCqHc/omoLUS6/BjcbsXyS/ns6d5Zv0fKVHumZ23V2qVJwPpmNdpkdfBhw
    HFKm0HLPaCyKM38fOPhrUwEW8OceVdHfBnkkAyYXA9+9qGF3gHC3MXMLkaH6pDYY
    Nfx2P4+qYnMnTMSOOvKsJWY7t8Tnv1Qotag/uW8yWlIBSnvg1BQ7u1ZJs1EKSwhw
    QbIrYj+eS+e8ddN7qSHJToMzHstTjSYQThA1iCVU6S+KHaLFeynf1d6PqkyeH/GD
    bk+E+hu5AQ0EXL1DqwEIANhU5FczwquEAcjhA+kf+ni0Ul9Q2aq+rAL31dg+sGMZ
    awcDu5aocwolXeBIkVl235GFfJSdYRzIbk5lSqVK+Wt5Yj4yOIO+QEAk5I51dzOC
    5i3APTqOM0UPQ168ubcoT5LY/aWLJqnVAjgY/Sn2vXAwsYvkuJZMpeOPoNgocAWw
    wGxXkPEy//OA3rwyy6PER2U7xLWL5SOH8oxjnsnHA98nF4iuOQqbwPTwfyWN7xr7
    HAY6KiawHmD0T3ywswR1bEZ1CYn8KxpNMuHf7tbaMPONvawVEqM1xc9+4tB3ImdM
    UB9eIiwIspq68mdE43eyUeM9f2foNR67Kj6F7hvBwDsAEQEAAYkBNgQYAQgAIBYh
    BNBHYbEWIDsMCFm2Fii3bgW5I4iOBQJcvUOrAhsMAAoJECi3bgW5I4iOLCAIANNd
    BwFFJpTaEZhOvDEsfOmHDFE+xG2fBq+SO53A4M/4xfJ6BVnpRvAgPvEu/ED8LMIB
    buaMUpXjAwULIOnNEBsYem+m3IKcrZAIhfXAjI8EqzprjciUiVEx0+XR6eIbsFm2
    gm61vHfbviKSyQg3hpKG8/g2sFgQ9CNi5DFghIYesp+7NwCC+UOVGBu90O4SIq+I
    Ms2n3OTR2GIEz0LgEvC/3R7pkBNjLNTccExBNqOShJy3XnwntvYflxVwEBVsyEbK
    LvLU2xtlIE/IdGssKQR8UFFsgFmGiX3t1TcahFnLlr6Et+vB4J02Xr+uvZ81v/Zq
    1OHz7iIjrd28MslYu24=
    =xMCa
    -----END PGP PUBLIC KEY BLOCK-----
  verifier-public-key-openshift-ci-2: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----
    Version: BCPG v1.63

    mQINBGCIN7cBEADMU21mvdiAgm5zQiaP7qF2ldj5udH9KII+kD8LIQy0s8ITQSmE
    iq2oJ58HuprRS6Zyorz9N8XVf+ivVRV71Ii5+0b5ErXz1b1kp/WzqxxlCdmOXW3E
    o4E665lNWLrrWNEtzguOdZ9LwDsUBoCSmaDB0aqHHZWk2jxtHuUmdsKS9K2ySowI
    67uUWl3WokUiLShhDdpqF3tWQ8BtOelsi621bypfJfXkki/vlgNN+gYkkxzDpHlC
    ckqh4THhw/rtvcXtMUGT0b1PMxK8xLn5WM7fkd1VXyrRG6FJsBBk4bPP7Y8PAXqN
    rfpmybpx6UPr8iOtWuuvmsIOFk1e7+zz72/Dn9ZzXLgZeNmYNDbfAgg85UAc1jEJ
    wkswcJzRmv4Yi185Bv3A/+VmiK/NImPePBa3J6gsWGa93Fi4cxNeESWh986j0fmf
    pad6C/VflZeKtOcrXNBexjPv6KAk4fXz3lFI3UQBN9fNgrF8sf4WKOeQ16MZixPB
    QYcxM+F656z0PMMjsYo040c/a2anxbHgzXNSQI0qkNurkOUYA05TTtDzo5S2iref
    j74kTD+znyBTgrTmoacT3fhhrlp4koFZsMEePejwtHsmD48PZPBK6NpGAjbaO1Xi
    sAPLdYGINT/8iN4WB/NS0LeYYkl9ZHZxghIeet7lU432mkqKYjKQbyQI1wARAQAB
    tG9vcGVuc2hpZnQtY2ktcmVsZWFzZS1rZXkgKFRoaXMga2V5IGlzIHVzZWQgdG8g
    c2lnbiByZWxlYXNlcyBmcm9tIHRoZSBPcGVuU2hpZnQgQ0kgc3lzdGVtKSA8Y2Nv
    bGVtYW5AcmVkaGF0LmNvbT6JAlQEEwEIAD4WIQQgzMetJy3NOqFp8SplwoNx9V0p
    qQUCYIg3twIbAwUJA8JnAAULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAKCRBlwoNx
    9V0pqXljEACt30mVRfi5gnWoEq7HWoc6QTdARLbeLf4Zo0LxcgnZMG5/btbrz0tl
    ymefnwV24o28bO0wnAxYS0+wVEope2PBf+PRk6WHGHg/+0q/cmAirrOh44tyONjZ
    kCioaqIeir8r02eC0dFmAkItKgv85sNF7XPnJk7kPgP4JAIWCijeEa1Y/LvT0JP3
    HpL7r0hxRVM8TOkULZphkezYXKRIik5BJ3DFYXMsyLc97VKb7afyKd6b1BclkBDv
    FVFQtPBEVpfJ0l7vPoQ05YT+RwR9VE7Bgws8JE1uOAOMwMEp3FgVtMhd88OlJc0t
    +wbcFVYbsVtw4S9M28lLRzp+DF+Lzmfu3vrfk7ptb1N0wPt8p20lbL6sHs9INclH
    pV0eCqf0B/IQU+8loJAFZ1Eri5kO9IugG7pLp+B8E2AZwZEqB2BVveoGi4Bf+yug
    Vs0AjmrJIw7Bc/JAwdVOa8e918tIVdyYay1InPQVO2t8R7maKveIyvYagJq5JlJS
    xtyi+JEMsrCkuAoPBzED2tqVOoIVxR3gU9v5bR2u+U6vDnDsduj5/Ept2s7qYtII
    yvNuntPtaM+MMZoG7uyDsdULjQpefn/JjFp5YWPkb+lIWhASFXmzLGStzA8nQF72
    SybvVav2YSz2YScI6ytxWUNzdQXRbqM/NUd2Ou1ycnybi0BiGeALYA==
    =v1yy
    -----END PGP PUBLIC KEY BLOCK-----
kind: ConfigMap
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/verification-config-map: ""
  creationTimestamp: null
  name: release-verification
  namespace: openshift-config-managed
